# Generated by Django 3.2.3 on 2021-05-16 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='goldRates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=256)),
                ('oneGramRate', models.CharField(max_length=256)),
                ('soverignRate', models.CharField(max_length=256)),
                ('tenGramRate', models.CharField(max_length=256)),
                ('difference', models.CharField(max_length=256)),
                ('state', models.CharField(max_length=256)),
            ],
        ),
    ]
