# Generated by Django 3.2.3 on 2021-05-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleModel', '0002_goldrates_purity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goldrates',
            old_name='difference',
            new_name='differencePerGram',
        ),
    ]
