# Generated by Django 3.2.3 on 2021-05-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teleModel', '0004_goldrates_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userId', models.CharField(max_length=512)),
                ('isAdmin', models.BooleanField(default=False)),
                ('addedBy', models.CharField(max_length=512)),
                ('addedOn', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
