# Generated by Django 3.2.3 on 2021-05-19 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teleModel', '0008_users_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='name',
        ),
    ]
